### PR TITLE
Implemented `Snapshot.export`

### PR DESCRIPTION
**Pull request by 3y3**
For @thlorenz review.

### CODE REVIEW

**Comment by thlorenz** [comment]
Looks nice after quick review and should solve the problem I was trying to tackle in #55.
I'll review this in more detail and give you better feedback by Monday.

**Comment by 3y3** [comment]
@thlorenz , Ok, thanks.
@bajtos , any thoughts?

**Comment by bajtos** [comment]
I'd say the solution is overcomplicated, it should be enough to support the flavour `export().pipe()`. Everything else can be achieved by stream composition, there is no need to repeat it in v8-profiler.

**Comment by 3y3** [comment]
@bajtos , are you propose to return `Writable` stream if there are no arguments passed to function, or you also propose to completely remove callback strategy for this method?

**Comment by bajtos** [comment]
> are you propose to return Writable stream if there are no arguments passed to function, or you also propose to completely remove callback strategy for this method?

Yes and yes.

See [concat-stream](https://www.npmjs.com/package/concat-stream) for an example of converting a stream-based interface to a callback-based one.

**Comment by bajtos** [comment]
Code sample:

```js
var callback = function(err, data) { /*...*/ };
var concatStream = require('concat-stream')(function(data) { callback(null, data); });
profiler.takeSnapshot().export()
  .on('error', callback)
  .pipe(concatStream)
  .on('error', callback);
```

**Comment by bajtos** [comment]
Also `toStream()` may be a better method name than `export`.

**Comment by 3y3** [comment]
>Also toStream() may be a better method name than export.

I take `export` name, because I want to implement also `import.snapshot` method.
Completed API will look like:
```js
var fs = require('fs') ;

profiler.gc().takeSnapshot().export() // We don't need to keep snapshot in memory
  .pipe(fs.createWriteStream('snapshot1'))
  .on('finish', profiler.gc)
  .on('finish', function test() {
    // Do something here.
    //...
    compareHeapState();
  });

function compareHeapState() {
  var currentHeap = profiler.takeSnapshot(),
    startHeap = profiler.import.snapshot('snapshot1');

  return currentHeap.compare(startHeap);
}
```

Exactly we don't have `gc` method now =)

**Comment by eljefedelrodeodeljefe** [comment]
@3y3 are you moving forwards with this?

**Comment by 3y3** [comment]
Landed.
I prefer to keep callback api, because not a good idea to install external dependencie only to have ability to save snapshot.

**Pull request closed without merging**
