### PR TITLE
Upgrade to nan v2.0.5

### PR DESCRIPTION
**Pull request by thlorenz**
- most changes applied via:
  https://gist.github.com/thlorenz/7e9d8ad15566c99fd116
- minor manual fixes applied
- heap_snapshot.cc: worked around fact that GetUid and GetTitle were
  removed from v8-profiler API
- heap_profiler.cc: fixed call to TakeHeapSnapshot to no longer pass a
  title
- using Nan::Persistent instead of v8::Persistent
- removing `HandleScope` from NAN_METHOD`s since they are provided in that
  case already

I was able to build directly with node 3.x (integrated v8-profiler source files and used `_linkedBinding`).

Testing with node-gyp has mixed results.
I'm running: `node-pre-gyp reinstall --build-from-source`

But with iojs 3.1 I get:

```
gyp http GET http://nodejs.org/dist/v3.1.0/node-v3.1.0.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 165.225.133.150:80
```
Maybe I'll try that part later if this is a server issue (not sure).

Similarly for iojs 2.5:

```
gyp http GET http://nodejs.org/dist/v2.5.0/node-v2.5.0.tar.gz
gyp http 404 http://nodejs.org/dist/v2.5.0/node-v2.5.0.tar.gz
gyp WARN install got an error, rolling back install
```

With older nodes it at least starts building, but complains about `Set` method signature, i.e.:

```
../src/cpu_profiler.cc:80:27: error: no matching member function for call to 'Set'
    info.GetReturnValue().Set(Profile::New(profile));
```

Hoping for some nan expert like @rvagg or @kkoopa to lend some advice.

### CODE REVIEW

**Comment by thlorenz** [comment]
Noticing failing tests on travis for older nodes and saw ` node-pre-gyp install --fallback-to-build` trick to properly run `node-gyp`.
Will have a look to fix those as soon as I get a chance.

**Comment by thlorenz** [comment]
This compiles and tests fine directly against iojs 3.1, but I can't get any to work with node-gyp.

I'm running: `node-pre-gyp reinstall --build-from-source`

But with iojs 3.1 I get:

```
gyp: /Users/thlorenz/.node-gyp/3.1.0/common.gypi not found (cwd: /Volumes/d/dev/v8-profiler) while reading includes of binding.gyp while trying to load binding.gyp
gyp 
```

With older nodes it at least starts building, but complains about `Set` method signature, i.e.:

```
../src/cpu_profiler.cc:80:27: error: no matching member function for call to 'Set'
    info.GetReturnValue().Set(Profile::New(profile));
```

Hoping for some nan expert like @rvagg or @ kkoopa to lend some advice.

**Comment by 3y3** [comment]
Please update also `.travis.yml` and `appveyor.yml` you can get actual versions from `v-debug` project

**Comment by thlorenz** [comment]
Done (basically just updated the matrix).

**Comment by thlorenz** [comment]
Closing in favor of #71 which includes the changes here plus some fixes on top of them to make it really work for all nodes.

**Pull request closed without merging**
