### PR TITLE
[WIP] Support Node 10

### PR DESCRIPTION
**Pull request by tcolgate**

### CODE REVIEW

**Comment by tcolgate** [comment]
This fails horribly at the moment.

**Comment by tcolgate** [comment]
This actually passes the tests but is horribly unsafe.
it seems that the right thing to do would be to wrap the v8 profiler created from the isolate and then store that on the CpuProfiler nan object. At present this is a little beyond me (at least in the time I can allocate)

**Comment by tcolgate** [comment]
Closing this PR. I'll leave my repo/branch for reference if people find this and are interested.

**Comment by Matt-Esch** [comment]
@tcolgate can you elaborate a bit more on what is unsafe about this? I might be able to find some time to pick it up.

**Comment by tcolgate** [comment]
The profiler is accessed without any locking. I have only slightly more than no idea what I'm doing in C++.

**Comment by Matt-Esch** [comment]
Are there multiple threads in competition for the profiler?

**Comment by tcolgate** [comment]
I've no idea, but read and write of that variable /probably/ needs to be
more controlled.

**Comment by tcolgate** [comment]
There have been no commits on this project for 2.5 years.  I'm not holding out any hope.

**Pull request closed without merging**
