### PR TITLE
add ability to get lineTicks in cpu profile

### PR DESCRIPTION
**Pull request by ofrobots**
This patch makes it possible to get line-ticks inside functions.

### CODE REVIEW

**Comment by ofrobots** [comment]
Fixing it for older versions.

**Comment by 3y3** [comment]
@ofrobots , thanks for contribution. Before deep review, can you please replace `auto` on variable type. Current implementation complicates checking of variable scope.

**Comment by ofrobots** [comment]
I have removed `auto` as requested. I'll look into the appveyor CI failure – the initial look suggests it is a network issue.

**Comment by ofrobots** [comment]
Oh I see that you have already merged this. Never mind.

**Comment by 3y3** [comment]
Sorry, that does not notify you. I was planning to do so before the next release. =)
Thank you for contribution.

**Pull request closed without merging**
