### PR TITLE
Improvements to CPU profiler

### PR DESCRIPTION
**Pull request by OleksandrChekhovskyi**
Expose more useful data from node.js

### CODE REVIEW

**Comment by OleksandrChekhovskyi** [comment]
Some builds are failing because of errors downloading node.js releases, not because of problems with patches.

**Comment by 3y3** [comment]
@OleksandrChekhovskyi , thank you for contribution.
Please look at my inline comments.

**Comment by OleksandrChekhovskyi** [comment]
I have updated the first patch, because I've noticed a compiler warning in CI builds. Also see my replies to inline comments.

**Comment by 3y3** [comment]
Reasonable comments.
Landed as 510542cedc6d8ed3618141ebb3d9674370f5fe6d

**Pull request closed without merging**
